#!/bin/bash
## ########################################################################## ##
## includes:
source ./part1.ini

## -------------------------------------------------------------------------- ##
SELECTED_USER="xxx";
USER_POSTFIX="-common"
LAYER_NO="8"

## includes:
source ../func_packages   ##

## -------------------------------------------------------------------------- ##
USER_SPECIFIC_PACKAGE="${PACKAGE_DIR_NAME}-env-${SELECTED_USER}${USER_POSTFIX}"

WORKING_DIR_LIST=(
"${PACKAGE_DIR}"
"${BASE_DIR}/${PACKAGE_DIR_NAME}-base"
"${BASE_DIR}/${USER_SPECIFIC_PACKAGE}"
)

SCRIPT_PATH="$PWD"
TEMP_COLLECTION_DIR="xxx"
OUTPUT_PATH="${SCRIPT_PATH}/${TEMP_COLLECTION_DIR}/data"

LAYER_DIR="${BASE_DIR}/LAYER/third-party_v${VERSION}-${SELECTED_USER}${USER_POSTFIX}"

SET_USER_RIGHTS_FOR_OPT="true"

## ########################################################################## ##
