#!/bin/bash
## ########################################################################## ##
## includes:
source ../version.ini

LOG_DATE=$(date +%F_%T)

BASE_DIR=".."

PACKAGE_DIR_NAME="third-party-packages"
PACKAGE_DIR="${BASE_DIR}/${PACKAGE_DIR_NAME}_${VERSION}"
PACKAGE_FILE="package.src"
DATA_DIR_LIST="data data_i386 data_amd64"

## ########################################################################## ##
